In [ ]:
import numpy as np
from numpy import linalg as la

A = np.array([
    [2,1],
    [1, 2]
])

w, v = la.eig(A)

In [14]:
A_10 = v @ np.diag(w**10) @ la.inv(v)
A_10

array([[29525., 29524.],
       [29524., 29525.]])

In [23]:
B = np.array([
    [1, 1],
    [0, 2]]
)

b_eigenvalues, b_eigenvectors = la.eig(B)
np.sum(b_eigenvectors@(np.diag(b_eigenvalues**10))@la.inv(b_eigenvectors))

np.float64(2048.0)

In [ ]:
C = np.array([
    [1, 6],
    [5, 2]
])

v_1 = np.array([1,0])
v_2 = np.array([6,5])
v_3 = np.array([1,-1])
v_4 = np.array([1,1])
v_1*7 == C@v_1, v_2*7==C@v_2, v_3*7==C@v_3, v_4*7==C@v_4 

(array([False, False]),
 array([False, False]),
 array([False, False]),
 array([ True,  True]))

In [29]:
w=np.array([2,3])
np.diag(w**3)

array([[ 8,  0],
       [ 0, 27]])